// Bundles the panel into a single ES module that the integration serves as a
// static file. The output is committed: people installing this have Home
// Assistant, not Node.
import { build, context } from "esbuild";
import { mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outfile = resolve(here, "../custom_components/matterbook/panel/matterbook-panel.js");

const dev = process.argv.includes("--dev");
const watch = process.argv.includes("--watch");

mkdirSync(dirname(outfile), { recursive: true });

/** @type {import("esbuild").BuildOptions} */
const options = {
  entryPoints: [resolve(here, "src/main.ts")],
  outfile,
  bundle: true,
  format: "esm",
  // Home Assistant 2026.x supports evergreen browsers only; this is well within
  // what the frontend itself targets.
  target: ["es2021"],
  minify: !dev,
  sourcemap: dev ? "inline" : false,
  legalComments: "none",
  banner: {
    js: "/* MatterBook panel — generated by panel/esbuild.config.mjs, do not edit. */",
  },
};

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log(`watching; writing ${outfile}`);
} else {
  await build(options);
  console.log(`wrote ${outfile}`);
}
